### ISSUE TITLE
Redesign the character sheet

### ISSUE THREAD

**Issue by brekiy** [brekiy/Codex#4]
As is, it's pretty ugly and presents the user with a lot of text boxes that they have to fill out. I should draw something out.

One thing I'm thinking of takes inspiration from the items page - there's a set of buttons that brings up the items by category in a dynamic fashion. I won't be doing that here since the static site doesn't store a user's character - instead what it will probably do is be broken into the sections that I've labeled within the HTML: so core stats, skills/perks, inventory, and biography/background.

A user clicks on one of the buttons to bring up the text boxes for ONLY that section - so if I clicked on the inventory button, I only see what my character's got in their inventory. It might force users to use more clicks to get something done, but I think the tradeoff in readability is worth it.

Saving/uploading the JSON shouldn't be changed. All that would happen behind the scenes is setting some div's display style to `none`.

**Comment by xiaohuynh** [comment]
Most of the changes I mentioned here are made. The character sheet has buttons acting as tabs that separate related attributes onto their own sections.
